// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPosts,
  DefaultPostsProps
} from "./plasmic/supabase/PlasmicPosts";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { User, Session } from "@supabase/gotrue-js";
import { supabase } from "../api";
import { repeatedElement } from "@plasmicapp/host";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface PostsProps extends Omit<DefaultPostsProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPostsProps altogether and have
// total control over the props for your component.
export interface PostsProps extends DefaultPostsProps {}

function Posts_(props: PostsProps, ref: HTMLElementRefOf<"div">) {
  return <PlasmicPosts 
    root={{ ref }} 
    {...props}
  />;
}

const Posts = React.forwardRef(Posts_);
export default Posts;
