// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i6YZmFxPJB69NEUgdf79ap
// Component: CMwFD5Szx-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import LoginComponent2 from "../../LoginComponent2"; // plasmic-import: LwABaAx8M7U/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_supabase.module.css"; // plasmic-import: i6YZmFxPJB69NEUgdf79ap/projectcss
import sty from "./PlasmicLoginPage2.module.css"; // plasmic-import: CMwFD5Szx-/css

export type PlasmicLoginPage2__VariantMembers = {};

export type PlasmicLoginPage2__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginPage2__VariantsArgs;
export const PlasmicLoginPage2__VariantProps = new Array<VariantPropType>();

export type PlasmicLoginPage2__ArgsType = {};
type ArgPropType = keyof PlasmicLoginPage2__ArgsType;
export const PlasmicLoginPage2__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginPage2__OverridesType = {
  root?: p.Flex<"div">;
  loginComponent2?: p.Flex<typeof LoginComponent2>;
};

export interface DefaultLoginPage2Props {}

function PlasmicLoginPage2__RenderFunc(props: {
  variants: PlasmicLoginPage2__VariantsArgs;
  args: PlasmicLoginPage2__ArgsType;
  overrides: PlasmicLoginPage2__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <LoginComponent2
            data-plasmic-name={"loginComponent2"}
            data-plasmic-override={overrides.loginComponent2}
            className={classNames("__wab_instance", sty.loginComponent2)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "loginComponent2"],
  loginComponent2: ["loginComponent2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  loginComponent2: typeof LoginComponent2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginPage2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginPage2__VariantsArgs;
    args?: PlasmicLoginPage2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLoginPage2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLoginPage2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginPage2__ArgProps,
      internalVariantPropNames: PlasmicLoginPage2__VariantProps
    });

    return PlasmicLoginPage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginPage2";
  } else {
    func.displayName = `PlasmicLoginPage2.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginPage2 = Object.assign(
  // Top-level PlasmicLoginPage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    loginComponent2: makeNodeComponent("loginComponent2"),

    // Metadata about props expected for PlasmicLoginPage2
    internalVariantProps: PlasmicLoginPage2__VariantProps,
    internalArgProps: PlasmicLoginPage2__ArgProps
  }
);

export default PlasmicLoginPage2;
/* prettier-ignore-end */
